### ISSUE TITLE
streamresolver not working with .stream files

### ISSUE THREAD

**Issue by JuliusThms** [WowzaMediaSystems/wse-plugin-streamresolver#4] opened 2017-05-16 22:12 UTC
Hello,

the streamresolver is working fine with rtmp streams pushed to origin server.
It seems that .stream files which are pulling rtsp (mediacaster rtp) are not working at the edge streamresolver.

Is this a known issue?

**Comment by rogerlittin** [comment] 2017-05-16 22:17
Hi,

this is an issue that we have been working to resolve but have been unable to replicate it. I added some extra debug logging yesterday and would appreciate if you could test with this new version and provide some logs to examine. You can create a support ticket if you don't want to post log files here. Please just reference this issue.

Thanks,

Roger.

**Comment by JuliusThms** [comment] 2017-05-16 22:19
Hi Roger,

thanks for your quick response. 
Are you unable to reproduce the problem? Maybe i could help.
Of course, i can place the logs here.

**Comment by JuliusThms** [comment] 2017-05-16 23:26
@rogerlittin 

Even if i unpublish and publish a stream (streamrepeater edge), the streamresolver does not start as it has to do. You cannot retreive the stream. In this case i tested the push method on the origin. An the stream ran at the first start.

**Comment by rogerlittin** [comment] 2017-05-17 01:05
Hi,

I'm not sure I understand what the problem is. Can you send me your config files and log files.

Thanks,

Roger.

**Comment by JuliusThms** [comment] 2017-05-17 08:23
Hi Roger,

i'll test, and give you the results. We have configured a long streamTimeout of 40 Seconds, maybe that is a Problem.

**Comment by JuliusThms** [comment] 2017-05-20 13:36
It seems that is a problem with the Wowza Version, we installed now the latest. Keep you updated.

**Comment by JuliusThms** [comment] 2017-05-20 21:58
@rogerlittin tested it, with debug mode. Still not working, if i request the manifest.f4m File sanjose, i'm always getting 404. Tried rtmp and wowz

`
INFO	application	comment	2017-05-20	21:50:48	-	-	-	-	-	11.053	-	-	-	-	-	-	-	-	ModuleStreamResolver.Lookup.run() before removing lookups for [live/_definst_/sanjosestreamingpacketizer_6003_Y7VgCf8HQTtpZML] lookups: {sanjosestreamingpacketizer_6003_Y7VgCf8HQTtpZML=Lookup: {streamName: sanjosestreamingpacketizer_6003_Y7VgCf8HQTtpZML, name: 6003_Y7VgCf8HQTtpZML, packetizer: sanjosestreamingpacketizer, startTime: 1495317048162, url: rtmp://origin2/live/_definst_/6003_Y7VgCf8HQTtpZML}}
INFO	application	comment	2017-05-20	21:50:48	-	-	-	-	-	11.053	-	-	
`

**Comment by rogerlittin** [comment] 2017-05-21 00:19
Hi,
I've just committed an update that checks to see the name passed into the resolveStreamAlias methods has already been resolved and if so just return it instead of trying to resolve it.

Can you please try that and see if it works. You will have to build from the source because I can't update the jar until Monday.

Roger.

**Comment by JuliusThms** [comment] 2017-05-21 07:07
Hi Roger, 

thanks for your quick response, i built the new jar file with your changes. I does not seem to be fixed. Here is the output, the original hostname of the origin servers is like ny-live-origin.domain.tld, i changed them in the logs to origin1 and origin2.

`
INFO	application	comment	2017-05-20	21:50:48	-	-	-	-	-	7.52	-	-	-	-	-	-	-	-	ModuleStreamResolver.resolveStreamAlias getting url for [live/_definst_/sanjosestreamingpacketizer_6003_Y7VgCf8HQTtpZML] urls: {sanjosestreamingpacketizer_6003_Y7VgCf8HQTtpZML=rtmp://origin2/live/_definst_/6003_Y7VgCf8HQTtpZML}
INFO	application	comment	2017-05-20	21:50:48	-	-	-	-	-	7.52	-	-	-	-	-	-	-	-	ModuleStreamResolver.resolveStreamAlias got url for [live/_definst_/sanjosestreamingpacketizer_6003_Y7VgCf8HQTtpZML]: url: rtmp://origin2/live/_definst_/6003_Y7VgCf8HQTtpZML, urls: {sanjosestreamingpacketizer_6003_Y7VgCf8HQTtpZML=rtmp://origin2/live/_definst_/6003_Y7VgCf8HQTtpZML}
`

**Comment by JuliusThms** [comment] 2017-05-28 15:21
@rogerlittin 

Edit: 

Seems to be working, but many times i get 404 responses.
Try to debug.

changed wowzaResolverProtocol from rtmp to wowz. 
Seems to be running completly fine now.

**Comment by JuliusThms** [comment] 2017-05-28 18:37
@rogerlittin What is, if the origin server changes? That's not implemented, right?

**Comment by rogerlittin** [comment] 2017-05-29 02:46
Hi,

I've made some changes to reduce the number of lookups back to the origin server and to improve support for mediaLists (smil files). Please checkout the mediaList_support branch and see if that works better for you.

https://github.com/WowzaMediaSystems/wse-plugin-streamresolver/tree/medialist_support

Regards,

Roger.

**Comment by JuliusThms** [comment] 2017-05-29 05:48
Hi Roger,

seems to be working.
.stream files still not working.

Best J

**Comment by JuliusThms** [comment] 2017-05-29 10:18
Hi @rogerlittin 

We have many lines with: `HTTPStreamerAdapterBase.startLiveStreamRepeat : java.lang.NullPointerException|`

Do you know were this can come from? Maybe if there cannot be a origin resolved?

**Comment by rogerlittin** [comment] 2017-05-29 21:41
When you say that .stream files are still not working, is this .stream files on the origin or on the edge? If on the origin then the stream needs to be running before the edge can locate it. the edge cannot trigger a stream to start on the origin. If on the edge, the .stream files won't work because the stream resolver workflow uses the same APIs that .stream files use and replaces their functionality.

**Comment by rogerlittin** [comment] 2017-05-29 21:42
For the NPE, can you post the complete log line and also the version and build number for Wowza Streaming Engine.

**Comment by JuliusThms** [comment] 2017-05-29 21:45
I'll. Also ill test the streams with .stream repeaters on the origin again.
After your update the module is running fine and stable, only the nullpointer exceptions are there. But ill test in detail tomorrow and send you an report.

Great Work!

**Comment by akeller** [comment] 2020-02-24 19:57
Closing.

**Closed as completed by akeller** 2020-02-24 19:57 UTC
